config/routes.rb
Rails.application.routes.draw do
  resources :lists
  root 'lists#index'
  get 'home/delete_marked'
  get 'home/delete_all'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def delete_marked
        @delete_marked = List.where(:completed => true).destroy_all
        redirect_to root_url, notice: 'All marked items were successfully deleted.'
    end

    def delete_all
        @delete_all = List.destroy_all
        redirect_to root_url, notice: 'All items were successfully deleted.'
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @list = List.new
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to root_url, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to root_url, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>To do App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'navbar'%>
    
    <div class="container">
    <br/>
    <% if notice %>
      <%= render 'alert' %>
    <% end %>
   
    <%= yield %>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

app/views/lists/_alert.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/lists/_form.html.erb
<%
=begin%>
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>
  <% end %> 
<%
=end %>

<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="bordered">
    <div class="field">
      <%= form.label :description, class:"form-label" %>
      <%= form.text_field :description, class:"form-control" %>
    </div>

    <br/>

    <div class="field">
      <%= form.label :completed, class:"form-check-label" %>
      <%= form.check_box :completed, class:"form-check-input" %>
    </div>

    <br/>
    <div class="actions">
      <%= form.submit class:"btn btn-primary" %>
    </div>
  </div>
  
<% end %>

app/views/lists/_form_nav.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="box">
      <div class="field">
        <%= form.text_field :description, class:"form-control me-2", placeholder:"Type..." %>
      </div>

      <div class="actions1">
        <%= form.submit "Add", class:"btn btn-outline-success"%>
      </div>
    </div>

<% end %>

     

app/views/lists/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "To Do App", root_path, class:"navbar-brand" %>
    <%# <a class="navbar-brand" href="#">To Do App</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <%#links%>
      </ul>  
          <%= render 'form_nav', list: @list %>
    </div>
  </div>
</nav>

app/views/lists/edit.html.erb
<div class="card">
  <div class="card-header">
    <h1>Editing List</h1>
  </div>
    <%= render 'form', list: @list %>


    
  </div>
    <br/>
    <%= link_to 'Show', @list, class:"btn btn-success" %>
    <%= link_to 'Back', root_path, class:"btn btn-success", style:'margin-left: 5px' %>
</div>

app/views/lists/index.html.erb
<br/>
<table class="table table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Description</th> 
      <th colspan='2'>Tools</th>
    </tr>
  </thead>

  <tbody class="table-hover">
    <% @lists.each do |list| %>
      <% if list.completed %>
        <tr class="table-success">
          <td class="striker"><%= link_to list.description, edit_list_path(list), style:"text-decoration: none; color: black" %></td>   
          <td> 
            <%= form_with(model: list) do |form| %>
                <%= form.submit "Uncross ", class:"btn btn-outline-primary btn-sm" %>
                <%= form.check_box :completed, :checked => false, :style => "visibility: hidden"%>
              <% end %>
          </td>  
          <td><%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' }, style:"text-decoration: none", class:"btn btn-outline-danger btn-sm"  %></td>
        </tr>
      <% else %>
        <tr class="table-light">
          <td ><%= link_to list.description, edit_list_path(list), style:"text-decoration: none; color: black" %></td>   
          <td>
            <%= form_with(model: list) do |form| %>
              <%= form.submit "Cross Off", class:"btn btn-outline-success btn-sm" %>
              <%= form.check_box :completed, :checked => true, :style => "visibility: hidden"%>
            <% end %>
          </td>  
          <td><%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' }, style:"text-decoration: none", class:"btn btn-outline-danger btn-sm"   %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br/>

<%= link_to 'Delete Marked Items', home_delete_marked_path, data: { confirm: 'Are you sure?' }, class:"btn btn-success" %>
<%= link_to 'Delete All Items', home_delete_all_path, data: { confirm: 'Are you sure?' }, class:"btn btn-success", :style => "margin-left: 10px" %> 

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @list.completed %>
</p>

<%= link_to 'Edit', edit_list_path(@list), class:"btn btn-success" %>
<%= link_to 'Back', edit_list_path(@list), class:"btn btn-success", style:"margin-left: 5px" %>